use_frameworks!

platform :ios, '9.0'
install! 'cocoapods',
:generate_multiple_pod_projects => true,
:disable_input_output_paths => true,
:deterministic_uuids => false


target 'ClassExtension_Example' do
  pod 'ClassExtension', :path => '../'

  target 'ClassExtension_Tests' do
    inherit! :search_paths

    
  end
end
